import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { createGlobalStyle } from "styled-components";
import Head from "next/head";

const GlobalStyle = createGlobalStyle`
    *,*::before,*::after{
        margin:0;
        padding:0;
        box-sizing: border-box;
    }
    body,button,input {
      font-family: 'League Spartan', sans-serif;
      /* font-family: 'Poppins', sans-serif; */
      font-weight: 500;
      font-size: 16px;
      color: hsla(231, 28%, 7%, 1);
    }
`;

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <GlobalStyle />

      <Head>
        <title>Invoice App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
