import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { ThemeProvider, createGlobalStyle } from "styled-components";
import Head from "next/head";
import theme from "@/theme/theme";

const GlobalStyle = createGlobalStyle`
    *,*::before,*::after{
      margin:0;
      padding:0;
      box-sizing: border-box;
    }
    body,button,input {
      font-family: 'Space Grotesk', sans-serif;
      font-weight: 700;
      font-size: 16px;
      color: hsla(0, 0%,0%, 1);
      background-color: hsla(257, 67%, 51%, 1);
    }
`;

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <GlobalStyle />
      <Head>
        <title>Invoice App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Component {...pageProps} />
      </ThemeProvider>
    </>
  );
}
